start updating postinst to update conf file if needed

diff --git a/scripts/files/postinst b/scripts/files/postinst
--- a/scripts/files/postinst
+++ b/scripts/files/postinst
@@ -47,6 +47,10 @@ APP_DATABASE_PASS=$RET
 db_reset raspisms/database_password
 if [ -z "$APP_DATABASE_PASS" ] ; then APP_DATABASE_PASS=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1) ; fi
 
+#App static http url
+db_get raspisms/app_static_http_url
+APP_STATIC_HTTP_URL=$RET
+
 #App user
 db_get raspisms/app_user_email
 APP_USER_EMAIL=$RET
@@ -87,6 +91,34 @@ Admin: $APP_USER_ADMIN\n"
 error_report () {
     printf "\n\nError on line $(caller)\n\n";
     exit 1
+}
+
+ask_for_conf_file_update () {
+    CONF_FILE=$1
+
+    printf "The configuration file $CONF_FILE have been modified by package maintainer and conflict with you own modifications.\n"
+    while true; do
+        read -p "Do you want to replace your file with the maintainer one? [Y/n] : " confirm
+        if [ -z "$confirm" ]; then
+            confirm="y"
+        fi
+
+        case $confirm in
+            Y | y)
+                printf "\nReplace configuration file $CONF_FILE.\n"
+                return 0; break
+                ;;
+
+            N | n) 
+                printf "\nDo not replace configuration file $CONF_FILE.\n"
+                return 1
+                ;;
+
+            *) 
+                printf "\nInvalid answer, please answer with 'Y' or 'N'.\n"
+                ;;
+        esac
+    done
 }
 
 do_show_credentials () {
@@ -160,10 +192,6 @@ do_phinx () {
 
 
 do_app_config () {
-    if [ "$IS_UPDATE" = true ]; then
-        return 0
-    fi
-
     printf "\n"
     printf "Do configuration of RaspiSMS app...\n"
 
@@ -177,7 +205,10 @@ do_app_config () {
     
     printf "  Replace APP_SECRET : \n"
     find . -type f -name "*.dist.local" -exec replace '%APP_SECRET%' "$APP_SECRET" -- {} \;
-   
+
+    printf " Replace APP_STATIC_HTTP_URL : \n"
+    find . -type f -name "*.dist.local" -exec replace '%APP_STATIC_HTTP_URL%' "$APP_STATIC_HTTP_URL" -- {} \;
+
     if [ "$DATABASE_AUTO_CONF" = "true" ]; then
         printf "  Replace APP_DATABASE_HOST : \n"
         find . -type f -name "*.dist.local" -exec replace '%APP_DATABASE_HOST%' "$APP_DATABASE_HOST" -- {} \;
@@ -215,7 +246,23 @@ do_app_config () {
     printf "  Remove .dist.local extensions.\n"
     for f in *.dist.local
     do
-        mv $f `basename $f ".dist.local"`
+        FINAL_FILE=$(basename $f '.dist.local')
+     
+        #If file already exists, check if we must update, else create
+        if [ -f "$FINAL_FILE" ]; then
+            CURRENT_FILE_MD5=$(md5sum "$FINAL_FILE" | cut -d' ' -f1)
+            NEW_FILE_MD5=$(md5sum "$f" | cut -d' ' -f1)
+
+            #Only if file have changed on one part, ask for update and potentially update
+            if [ "$CURRENT_FILE_MD5" != "$NEW_FILE_MD5" ]; then
+                ask_for_conf_file_update $FINAL_FILE
+                if [ $? -eq 0 ]; then
+                    mv $f $FINAL_FILE
+                fi
+            fi
+        else
+            mv $f $FINAL_FILE
+        fi
     done
 
     printf "Done.\n"
